# gitops-manifests/namespaces/bankguard.yaml
# Namespace UNIQUE - le nom sera préfixé/suffixé par Kustomize
# selon l'environnement (dev, staging, prod)

apiVersion: v1
kind: Namespace
metadata:
  name: bankguard  # <-- Kustomize transformera en "bankguard-dev" ou "bankguard-prod"
  labels:
    app.kubernetes.io/name: bankguard
    app.kubernetes.io/part-of: bankguard-system
    app.kubernetes.io/managed-by: gitops
  annotations:
    description: "Namespace pour l'application BankGuard"
    owner: "sre-team"
