apiVersion: v1
kind: Secret
metadata:
  name: bankguard-secrets
  namespace: bankguard-dev
  labels:
    app.kubernetes.io/component: api
    app.kubernetes.io/managed-by: gitops
    app.kubernetes.io/name: bankguard-api
    app.kubernetes.io/part-of: bankguard-system
type: Opaque
stringData:
  DB_PASSWORD: dev_password_123
  REDIS_PASSWORD: dev_redis_123
