apiVersion: v1
kind: Secret
metadata:
  name: bankguard-secrets
type: Opaque
stringData:  # Utilise stringData pour texte clair (sera encodé automatiquement)
  DB_PASSWORD: fakepassword123
  REDIS_PASSWORD: redispass123
  SECRET_KEY: mysecretkey123456
  JWT_SECRET: jwtsecret789012
