apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: bankguard-dev
  labels:
    app.kubernetes.io/component: cache
    app.kubernetes.io/managed-by: gitops
    app.kubernetes.io/name: redis
    app.kubernetes.io/part-of: bankguard-system
spec:
  selector:
    app: redis
  ports:
  - name: redis
    protocol: TCP
    port: 6379
    targetPort: 6379
  type: ClusterIP
