apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: bankguard-monitor
  namespace: bankguard-dev
  labels:
    release: prometheus  # Doit matcher le label de votre Prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: bankguard-api
  endpoints:
  - port: http
    interval: 15s
    path: /metrics
    honorLabels: true
    relabelings:
    - sourceLabels: [__meta_kubernetes_pod_name]
      targetLabel: pod
